# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='version',
            new_name='question',
        ),
    ]
