# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='choice_id',
            new_name='choice',
        ),
    ]
