# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170826_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default='0001', on_delete=django.db.models.deletion.CASCADE, to='api.Question'),
            preserve_default=False,
        ),
    ]
