# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='What should we build next?', max_length=255),
            preserve_default=False,
        ),
    ]
