# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='choice',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='version',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
